chatmail/relay

- README.md
oops, the blogpost is out already.
> README: rework and reorder

- chatmaild/pyproject.toml
- chatmaild/src/chatmaild/doveauth.py
- chatmaild/src/chatmaild/echo.py
- chatmaild/src/chatmaild/echobot.service.f
- cmdeploy/src/cmdeploy/__init__.py
Send a message to echo@c5.testrun.org to try it out :)
fixes #109
> echobot: add echo bot for trying out sending

- www/src/info.md
> feat: one more paragraph to explain `chatmail`

- chatmaild/src/chatmaild/ini/chatmail.ini.f
- chatmaild/src/chatmaild/tests/test_config.py
- cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2
- cmdeploy/src/cmdeploy/www.py
- www/src/info.md
Does anyone have an idea how to test this?
> dovecot: unconditionally delete all mails after 40 days

- README.md
- cmdeploy/src/cmdeploy/__init__.py
- cmdeploy/src/cmdeploy/chatmail.zone.f
- cmdeploy/src/cmdeploy/cmdeploy.py
- cmdeploy/src/cmdeploy/dns.py
- cmdeploy/src/cmdeploy/tests/test_cmdeploy.py
> Improving UX of setting up DNS entries

- .github/workflows/ci.yaml
- cmdeploy/src/cmdeploy/cmdeploy.py
- cmdeploy/src/cmdeploy/dns.py
- cmdeploy/src/cmdeploy/tests/online/test_0_login.py
- cmdeploy/src/cmdeploy/tests/test_cmdeploy.py
fixes #142 
fixes #144
fixes #140 
fixes #143
> cmdeploy: fail init and run if SSH doesn't connect

- chatmaild/src/chatmaild/echo.py
> echo: fail if configure doesn't work

- cmdeploy/src/cmdeploy/postfix/main.cf.j2
> postfix: increase compatibility_level to 3.6

- cmdeploy/src/cmdeploy/__init__.py
- cmdeploy/src/cmdeploy/postfix/main.cf.j2
- cmdeploy/src/cmdeploy/postfix/master.cf.j2
- cmdeploy/src/cmdeploy/postfix/submission_header_cleanup
- cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py
replaces #155 
Somehow @nudeldudel's solution didn't work for me, now this should work and there is a test to ensure it :)
> Header cleanup

- .github/workflows/staging.testrun.org-default.zone
- .github/workflows/test-and-deploy.yaml
- cmdeploy/src/cmdeploy/__init__.py
- cmdeploy/src/cmdeploy/cmdeploy.py
- cmdeploy/src/cmdeploy/dns.py
> CI run to deploy on staging.testrun.org

- cmdeploy/src/cmdeploy/chatmail.zone.f
- cmdeploy/src/cmdeploy/dns.py
> Do not subscribe to TLS reports

- cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py
> test that echobot replies

- cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2
> dovecot: increase default_client_limit

- cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2
> expunge: reset maildirsize after expunging old mails

- cmdeploy/src/cmdeploy/acmetool/acmetool.cron
> acmetool: reload postfix+dovecot after cert renew.

- chatmaild/src/chatmaild/doveauth.py
- chatmaild/src/chatmaild/tests/test_doveauth.py
> be silent on regular hello-message in dictproxy doveauth protocol

- CHANGELOG.md
- chatmaild/src/chatmaild/doveauth.py
- chatmaild/src/chatmaild/metadata.py
- cmdeploy/src/cmdeploy/__init__.py
- cmdeploy/src/cmdeploy/dovecot/auth.conf
- cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2
- cmdeploy/src/cmdeploy/service/chatmail-metadata.service.f
- cmdeploy/src/cmdeploy/service/doveauth.service.f
Also sandbox chatmail-metadata
Fixes #260
> Run chatmail-metadata and doveauth as vmail

- CHANGELOG.md
- cmdeploy/src/cmdeploy/__init__.py
> Fix multiple obs repos in /etc/apt/sources.list #272

- cmdeploy/src/cmdeploy/__init__.py
> Add acl to apt.packages

- cmdeploy/src/cmdeploy/acmetool/__init__.py
related to #302, should give us some rest until we can find the actual cause.
> CI: disable requesting new certs for staging.testrun.org

- CHANGELOG.md
- chatmaild/src/chatmaild/ini/chatmail.ini.f
- chatmaild/src/chatmaild/tests/test_config.py
> change delete_mails_after default to 20

- .github/workflows/test-and-deploy.yaml
- README.md
this should fix #231 (and arguably #287) or would you prefer a longer explanation? I felt a long paragraph would be overkill in comparision to the rest of the short documentation.
I haven't written into the changelog, as this is doesn't touch the code, is this the right way?
> Recommend authentication via ssh key with ed25519 algorithm (#231)

- cmdeploy/src/cmdeploy/__init__.py
> Ensure cron is installed

- www/src/index.md
- www/src/info.md
- www/src/privacy.md
The privacy policy now has a clear summary, noting that it might not even be neccessary to provide one but we do it anyway.
> refine privacy policy and conditionally adapt for nine-default onboarding

- CHANGELOG.md
- cmdeploy/src/cmdeploy/cmdeploy.py
- cmdeploy/src/cmdeploy/dns.py
> DNS: don't check DNS on cmdeploy init anymore

- .github/workflows/ci.yaml
- .github/workflows/staging.testrun.org-default.zone
- .github/workflows/test-and-deploy.yaml
- cmdeploy/src/cmdeploy/acmetool/__init__.py
Fixes #302
(and fixes #301, as this was just a semi-related, small change.)
> Change CI to staging2.testrun.org to fix acme problems

- CHANGELOG.md
- cmdeploy/src/cmdeploy/dns.py
- cmdeploy/src/cmdeploy/remote_funcs.py
partly addresses #336 
if someone wants to care for PTR they can still do it.
> don't do PTR reverse checking

- CHANGELOG.md
- chatmaild/src/chatmaild/delete_inactive_users.py
- chatmaild/src/chatmaild/ini/chatmail.ini.f
- chatmaild/src/chatmaild/tests/test_delete_inactive_users.py
On nine there are some 100Ks of old users, so we delete in chunks of 100 to speed it up.
> chunked deletion of stale users

- chatmaild/src/chatmaild/tests/mail-data/encrypted.eml
- chatmaild/src/chatmaild/tests/plugin.py
- chatmaild/src/chatmaild/tests/test_filtermail.py
this should fix what wasn't quite right yet about #369 but wasn't detected because the CI runs not well for outside-collaborators.
> fix maildata handling after prematurely merging #369

- chatmaild/src/chatmaild/dictproxy.py
- chatmaild/src/chatmaild/doveauth.py
- chatmaild/src/chatmaild/metadata.py
- chatmaild/src/chatmaild/tests/test_doveauth.py
- chatmaild/src/chatmaild/tests/test_metadata.py
Refactor common dictproxy-base code of metadata and doveauth services
so that it's easier to implement a new dictproxy for #352
> split out DictProxy for re-use from doveauth

- cmdeploy/src/cmdeploy/__init__.py
- cmdeploy/src/cmdeploy/service/filtermail.service.f
> run filtermail as dedicated user

- chatmaild/src/chatmaild/config.py
- chatmaild/src/chatmaild/ini/chatmail.ini.f
- chatmaild/src/chatmaild/tests/plugin.py
- chatmaild/src/chatmaild/tests/test_config.py
- cmdeploy/src/cmdeploy/dns.py
- cmdeploy/src/cmdeploy/postfix/main.cf.j2
fixes #268 and also fixes a format-string typo/error on the side.
> introduce max_message_size config option

- www/src/index.md
- www/src/main.css
> Add button to sign-up on chatmail server

- CHANGELOG.md
- chatmaild/src/chatmaild/ini/chatmail.ini.f
- chatmaild/src/chatmaild/ini/override-testrun.ini
> remove dysfunct hispanilandia ref

- README.md
> Document setting up DNAT

- CHANGELOG.md
- cmdeploy/src/cmdeploy/cmdeploy.py
> cmdeploy: add argument to specify different SSH host than mail_domain

- README.md
fix #464
Thanks for noticing @DexterNemrod!
> doc: fix migration guide

- CHANGELOG.md
- cmdeploy/src/cmdeploy/service/chatmail-metadata.service.f
- cmdeploy/src/cmdeploy/service/doveauth.service.f
> chatmaild: fix umask for doveauth + metadata

- CHANGELOG.md
- cmdeploy/src/cmdeploy/__init__.py
> opendkim: use su instead of sudo

- CHANGELOG.md
- chatmaild/src/chatmaild/filtermail.py
- chatmaild/src/chatmaild/tests/test_filtermail.py
fix #496 
added test coverage.
> filtermail: strip any empty lines at the end

- CHANGELOG.md
- cmdeploy/src/cmdeploy/mtail/mtail.service.j2
> mtail: fix getting logs from STDIN

- CHANGELOG.md
- cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2
> delete big messages after 7 days

- cmdeploy/src/cmdeploy/__init__.py
> opendkim: add absolute path to opendkim-genkey

- chatmaild/src/chatmaild/metrics.py
- chatmaild/src/chatmaild/tests/test_metrics.py
> fix metrics to check for "cur" mailbox instead of counting all subdirs

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
I would add the invite link to the mutual help chat group only if you agree that we can publish it :) But I think it could help operators a lot if they could ask in that group for support during setting it up
> Issue templates

- cmdeploy/src/cmdeploy/tests/online/test_1_basic.py
follow-up for #553, which failed in some situations.
> tests: check whether opendkim restarted in the last 48 hours

- README.md
@hpk42 asked me to add a note to the README about related projects, so that it's easier for other folks to find them. I've added my work on contributing to Mox here, and someone else may be adding Chef deployment recipes soon.
> Add note to README about related projects

- CHANGELOG.md
- cmdeploy/src/cmdeploy/remote/rdns.py
> cmdeploy: run apt update to make sure dns-utils can be installed

- cmdeploy/src/cmdeploy/__init__.py
If running in a constrained environment (e.g. an incus / systemd container), setting sysctl limits is constrained, this tweak just checks existing settings and if large enough continues instead of applying
> Only update sysctl settings if needed

- chatmaild/pyproject.toml
- cmdeploy/pyproject.toml
- cmdeploy/src/cmdeploy/__init__.py
this should make the CI green again.
> CI: ignore PLC0415 in ruff (imports outside top level)

- cmdeploy/src/cmdeploy/__init__.py
> echobot: restart after postfix + dovecot were started
