chatmail/relay

www/src/privacy.md

Add a single space to DeltaChat so it aligns how it is written in the rest of the document

fix: align spelling of Delta Chat

---

chatmaild/src/chatmaild/newemail.py

This expands the character set used for passwords generated for new
accounts.  The set it taken from the set used by the pass tool.  The
special characters is the full GNU grep [:punct:] set.

Use more characters for passwords

---

cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/deploy.py

Some of these changes are quite opinionated and we didn't discuss them yet, I'm fine to revert some of it.
I think it makes sense to add the nine.chatmail.ini to the repository, it is a good example and documents our main instance config. Also we can now easily consciously deploy nine.testrun.org with `cmdeploy --config nine.testrun.org run`.
I also think that for everyone else, the default username length should be 6 to 20; the limitation is funny for nine.testrun.org, but this makes it far easier to deploy a chatmail server and get the username you want. Whether the upper and lower limits are inclusive or not is documented in chatmail.ini, but nine.chatmail.ini also serves as an example.

get cmdeploy run --config working

---

cmdeploy/src/cmdeploy/acmetool/__init__.py
cmdeploy/src/cmdeploy/acmetool/acmetool-redirector.service
cmdeploy/src/cmdeploy/nginx/nginx.conf.j2

This avoids circular dependency with nginx.
nginx needs a certificate to start
and getting a certificate requires someone
listening on port 80.
Fixes #133

Let acmetool manage port 80

---

cmdeploy/src/cmdeploy/__init__.py

unbound: generate root.key manually if it doesn't exist

---

www/src/info.md

https://daleth.cafe/info.html doesn't have a reason to say "nine.testrun.org" ;)

www: change nine.testrun.org occurence to mail_domain

---

scripts/initenv.sh

This is to support Debian 11 which ships setuptools that do not support `-e` without setup.py
Fixes #192

Update `pip` and `setuptools` in scripts/initenv.sh

---

cmdeploy/src/cmdeploy/postfix/master.cf.j2

All these entries are related to `postscreen` service which is currently not enabled.
For documentation see https://www.postfix.org/POSTSCREEN_README.html
If we later want to enable it, we can readd uncommented entries and document it.

Remove postscreen-related entries from Postfix master.cf

---

chatmaild/src/chatmaild/ini/chatmail.ini.f
chatmaild/src/chatmaild/ini/override-testrun.ini
chatmaild/src/chatmaild/tests/test_config.py

This way, nine.testrun.org users can easily join groups and use the xstore. Additional benefit - admins can see the separator for lists in chatmail.ini at one glance.

config: add xstore and groupsbot to default passthrough_recipients

---

cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py

This also adds a test which admins can run to verify the cronjob is working correctly. I'm a bit conflicted about the test as it doesn't verify if a system works correctly *right now*, only that it worked correctly last night... but it will work on staging at least, as staging isn't old enough yet for the bug to appear :upside_down_face: 
fix https://github.com/deltachat/chatmail/issues/210

run expunge cronjob as correct user

---

cmdeploy/src/cmdeploy/tests/online/test_0_login.py

It seems we already return 252 for every VRFY command, so we neither confirm nor deny that a mailbox exists on the server. This is the desired behavior. I nonetheless added a test to avoid regressions.
This means our postfix is sufficiently hardened, I think?
replaces #168

tests: add test that we don't leak email addresses via VRFY

---

cmdeploy/src/cmdeploy/__init__.py

two admins already reported errors with `cmdeploy run` because rsync wasn't pre-installed on the server. Apparently pyinfra doesn't take care of this itself.

make sure rsync is installed, later commands depend on it

---

chatmaild/src/chatmaild/metadata.py
chatmaild/src/chatmaild/tests/test_metadata.py

Otherwise Dovecot times out when trying to iterate over metadata of the folder. Apparently it happens when attempting to delete folder from the server over IMAP.

Implement "iterate" command in metadata server

---

chatmaild/src/chatmaild/chatmail-metadata.service.f
chatmaild/src/chatmaild/metadata.py
chatmaild/src/chatmaild/tests/test_metadata.py

fixes #238 
note that i use "marshal", the python interpreter fast marshalling of basic data types. A dict[string->string] is pretty safe to marshal and demarshal, so nothing more fancy is needed.  Also tested that python3.6 and python3.10 can read/write the marhsalled data.

add persistent metadata/token storage

---

cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/dovecot/default.sieve

this PR pre-compiles the sieve-script added for ios push notifications .... 
in particular it fixes this error which made dovecot compile the (small) sieve script but then fail to write to `/etc/dovecot` the resulting "svbin" and so it would retry that on every incoming message. 
The comment in `default.sieve` is mostly to force the compile-step on all chatmail services. 
```
Mär 20 14:23:36 c2 dovecot[54426]: lmtp(ac1_vkst1@c2.testrun.org)<54671><iHSYH2jx+mWP1QAAwVJQ4w>: Error: open(/etc/dovecot/default.svbin.c2.54671.69dff114ef729adb) failed: Read-only file system
Mär 20 14:23:36 c2 dovecot[54426]: lmtp(ac1_vkst1@c2.testrun.org)<54671><iHSYH2jx+mWP1QAAwVJQ4w>: Error: sieve: binary /etc/dovecot/default.svbin: save: failed to create temporary file: open(/etc/dovecot/default.svbin.) …
```

fix runtime dovecot/sieve-compile error on every incoming message

---

cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py

addresses #235 a default `cmdeploy test` without the env-var passes  on c1 
Does not fully resolve test-runs as specifying CHATMAIL_DOMAIN2 to c1 or nine fails some tests because currently nine/c1 reject DKIM-sigs from c2-accounts.

fix some test and formatting/ruff issues

---

CHANGELOG.md
chatmaild/pyproject.toml
chatmaild/src/chatmaild/chatmail-metadata.service.f
chatmaild/src/chatmaild/filedict.py
chatmaild/src/chatmaild/metadata.py
chatmaild/src/chatmaild/tests/test_filedict.py
chatmaild/src/chatmaild/tests/test_metadata.py
cmdeploy/pyproject.toml
cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py

supersedes #243 
As discussed [here](https://github.com/deltachat/chatmail/pull/243#issuecomment-2022442764) it is possible to know the mailbox-dir for metadata get/set requests so this PR sets/gets devicetokens accordingly. 
This means that a mailbox-dir (the inbox folder of a user basically) contains also the metadata, now in the "metadata.marshalled" file in the inbox folder. 
The data is persisted using the builtin "marshal" module and guarded by an os-level file lock. 
The PR also adds both local as well as online tests, and adds support for GETMETADATA.

store devicetokens inside per-user mailboxdir, allow multiple tokens per account, support GETMETADATA and add tests

---

.github/workflows/test-and-deploy.yaml

The CI doesn't seem to restore Let's Encrypt and DKIM state properly, so it ran into Let's Encrypt rate limit: https://github.com/deltachat/chatmail/actions/runs/8477304659/job/23228081309?pr=261

CI: fix rsync statements

---

.github/workflows/test-and-deploy.yaml

The CI checks now whether the server has currently a useful ACME & DKIM state, stores it on ns.testrun.org, and if not, tries to find a useful ACME & DKIM state on ns.testrun.org before executing `cmdeploy run`.
This hopefully prevents CI runs, which wipe the server and then get cancelled prematurely, from deleting our ACME & DKIM state.

CI: restore ACME & DKIM state from ns.testrun.org

---

CHANGELOG.md
cmdeploy/src/cmdeploy/dns.py

fix #219 
I ran `apt remove dnsutils && apt autoremove` on staging.testrun.org to test it.

DNS: ensure dig is installed

---

CHANGELOG.md
chatmaild/src/chatmaild/metadata.py
chatmaild/src/chatmaild/notifier.py
chatmaild/src/chatmaild/tests/test_metadata.py

supersedes #263 
- uses a queue to keep notification ordering
- starts a couple of threads to handle "retry-buckets": a token with a failed notification requests goes into the next retry-bucket until it exceeds max number of buckets and it is dropped
- extensive tests also for the (rare) error cases 
- split "metadata" and "notification" logic into separate files

Keep notification ordering and back off failed notification attempts

---

CHANGELOG.md
cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/journald.conf
cmdeploy/src/cmdeploy/nginx/nginx.conf.j2

Stop logging IPs to storage

---

CHANGELOG.md
chatmaild/src/chatmaild/filtermail.py

They are not used by Delta Chat now,
but this will allow to start using them in the future.

Allow SKESK packets in encrypted mails

---

.github/workflows/test-and-deploy.yaml

Somehow our CI seems to fail again: https://github.com/deltachat/chatmail/actions/runs/9565324196/job/26379016754
This hopefully fixes it.

CI: accept ns.testrun.org host key

---

www/src/privacy.md

before, the order was 2 - 3.1 - 3.2 - 3
i think, the gist was to have subheadlines under "2."; this is fixed by this PR.
moreover, the PR contains a small typo fix.

fix headline ordering numbers, typo

---

CHANGELOG.md
cmdeploy/src/cmdeploy/__init__.py

which takes forever on servers with many mail directories
it's unclear why this is still needed and should be fixed differently in there is an actual problem.

remove fix-file-owner step 

---

.github/workflows/test-and-deploy.yaml
CHANGELOG.md
cmdeploy/pyproject.toml
cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/remote_funcs.py
cmdeploy/src/cmdeploy/sshexec.py
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py

shrinks and streamlines the DNS-checking code to use 'execnet' which allows to execute python functions remotely. 
- DNS-checking is much faster as the ssh-connection is re-used, and there are much fewer roundtrips. 
- Instead of parsing the output of the "ip" command this PR uses a standard python "socket" pattern to determine IPV4 and IPV6 addresses.  This is likely less dependent on the target enviroment, so could also work better with non-debian systems.  
- DNS checking now gives progress indicators (use -v|--verbose to see commands executed remotely)

feat: faster and simpler DNS checks, better ip-address determination

---

CHANGELOG.md
chatmaild/pyproject.toml
chatmaild/src/chatmaild/config.py
chatmaild/src/chatmaild/delete_inactive_users.py
chatmaild/src/chatmaild/doveauth.py
chatmaild/src/chatmaild/ini/chatmail.ini.f
chatmaild/src/chatmaild/remove_stale_users.py
chatmaild/src/chatmaild/tests/plugin.py
chatmaild/src/chatmaild/tests/test_config.py
chatmaild/src/chatmaild/tests/test_delete_inactive_users.py
chatmaild/src/chatmaild/tests/test_doveauth.py
cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2

fixes #295 
supersedes #327 
this adds a new chatmaild entry point `delete_inactive_users` which removes all user state for users which didn't log in for `delete_inactive_users_after` days (defaulting to 25).

automatically delete inactive users from database and mail directories 

---

CHANGELOG.md
chatmaild/src/chatmaild/config.py
chatmaild/src/chatmaild/delete_inactive_users.py
chatmaild/src/chatmaild/doveauth.py
chatmaild/src/chatmaild/ini/chatmail.ini.f
chatmaild/src/chatmaild/metadata.py
chatmaild/src/chatmaild/tests/plugin.py
chatmaild/src/chatmaild/tests/test_config.py
chatmaild/src/chatmaild/tests/test_delete_inactive_users.py
chatmaild/src/chatmaild/tests/test_doveauth.py
cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2
cmdeploy/src/cmdeploy/dovecot/expunge.cron.j2
cmdeploy/src/cmdeploy/metrics.cron.j2
cmdeploy/src/cmdeploy/service/chatmail-metadata.service.f
cmdeploy/src/cmdeploy/service/doveauth.service.f
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py

introduce two new config options and remove all hardcoding of user state directories, see changelog. 
`rg "/home/vmail"`  now only hits on the `chatmail.ini.f` file and the changelog but nothing in python or systemd files

remove all hardcoding of passdb and user mailbox dirs 

---

cmdeploy/src/cmdeploy/acmetool/acmetool.cron

This should fix reports of outdated TLS certs in NGINX, while postfix already has the more recent one.
Related: https://github.com/deltachat/pyinfra-acmetool/pull/2
Maybe we should update the version of pyinfra-acmetool we use in chatmail with the improvements we made in the package we use in the rest of our infrastructure.

acmetool: reload nginx after requesting new cert

---

cmdeploy/src/cmdeploy/postfix/master.cf.j2

Otherwise smtpd reduces it to 10s on "overload".
Fixes #315

postfix: fix timeout to 300s on submission ports

---

cmdeploy/src/cmdeploy/postfix/master.cf.j2

postfix was hitting the "100 clients" smtp-submission connected limit… (DC apps) and switched to stress mode which brings more randomness/relay to smtp-connections. We now allow 5K because it should be fine for the machine.

Instead of 100 smtp-submission processes allow 5K 

---

chatmaild/src/chatmaild/filtermail.py
chatmaild/src/chatmaild/tests/mail-data/encrypted.eml
chatmaild/src/chatmaild/tests/plugin.py
chatmaild/src/chatmaild/tests/test_filtermail.py

in draft-ietf-lamps-header-protection-22, hcp_minimal recommends "[...]" as the obscured Subject header.  In the pending draft -23 (hopefully released this week, going into a working group last call), the same HCP will be renamed to hcp_baseline, but it still recommends the use of "[...]" for the obscured Subject header.

Accept encrypted messages that use hcp_minimal

---

CHANGELOG.md
cmdeploy/pyproject.toml
cmdeploy/src/cmdeploy/cmdeploy.py

cmdeploy: skip warnings only in pyinfra 3; pyinfra crashes otherwise

---

cmdeploy/src/cmdeploy/tests/online/benchmark.py

Seemed to be broken since https://github.com/deltachat/deltachat-core-rust/commit/e16322d99dd102d24cd8b0136fa425d6812a5bd7:
```
================================================================================================================= FAILURES ==================================================================================================================
___________________________________________________________________________________________________________ TestDC.test_ping_pong ___________________________________________________________________________________________________________
self = <cmdeploy.tests.online.benchmark.TestDC object at 0x7e9371334bb0>, benchmark = <function benchmark.<locals>.bench at 0x7e93702dedc0>, cmfactory = <deltachat.testplugin.ACFactory object at …
```

tests: fix wait_next_incoming_message() in cmdeploy bench

---

chatmaild/src/chatmaild/doveauth.py

Currently logs look like this:
`Created address: <chatmaild.user.User object at 0x7fafac36bcd0>`

Fix doveauth logging for created accounts

---

CHANGELOG.md
chatmaild/src/chatmaild/config.py
chatmaild/src/chatmaild/ini/chatmail.ini.f
cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2

introduce imap_rawlog option for debugging

---

CHANGELOG.md
chatmaild/src/chatmaild/dictproxy.py
chatmaild/src/chatmaild/lastlogin.py
chatmaild/src/chatmaild/metadata.py

both metadata and lastlogin subclasses of DictProxies now don't need 
to know about transactions at all.

allow dictproxy subclasses to be ignorant of transactions in handle_set operations

---

CHANGELOG.md
cmdeploy/src/cmdeploy/__init__.py

fixes #397
we could also install "unattended-upgrades" but this might disrupt services at unexpected times so i left that out for now. 
ugprading only happens at "cmdeploy run" time.

upgrade debian packages on "cmdeploy run"

---

CHANGELOG.md
cmdeploy/src/cmdeploy/nginx/nginx.conf.j2

make nginx not listen on ipv6 if v6 is disabled. 

---

chatmaild/src/chatmaild/ini/chatmail.ini.f
www/src/info.md

fixes #405 
also lowers the inactive account deletion to 90 days by default.

add a note on deletion of accounts

---

CHANGELOG.md
cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2

I wanted to add `COMPRESS=DEFLATE`,
but it should be added only for sessions
that are logged in because `COMPRESS`
command does not work before logging in.
Dovecot already does it correctly
if we don't overwrite the capability string.

Add IMAP capabilities instead of overwriting them

---

.github/workflows/test-and-deploy-ipv4only.yaml
.github/workflows/test-and-deploy.yaml

It should be reliable since https://github.com/deltachat/chatmail/pull/424 is merged.

ci: test `cmdeploy dns` only once

---

cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/deploy.py

Migration is still not super nice because it required me to do a lot of back-and-forth in my local /etc/hosts file, and keep track of "which certificates are on which server now, where does DNS point already, and for who..."
But this made it work in principle.
Note that postfix will still be reachable for a while during the initial `cmdeploy run --disable-mail` command on the new server, so if DNS is already pointing to it, some messages will be sucked into the void. I will write a migration guide which avoids this.

cmdeploy: flag to disable postfix + dovecot for migration

---

README.md

fix #419 
I decided against mentioning that you can modify the chatmail.ini on the server and restart a chatmaild service to make it use the new value on runtime. Admins don't need to know that there is even a copy of the config file on the server; editing it is a bad idea anyway.

docs: more details for the repo overview

---

CHANGELOG.md
cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2

for consistency with the limit applied to Postfix

Dovecot quota_max_mail_size to use the Chatmail max_message_size value

---

CHANGELOG.md
README.md
cmdeploy/src/cmdeploy/cmdeploy.py

This guide doesn't require knowing about firewalls, but utilizes the `cmdeploy run --disable-mail` command from #428 and the `cmdeploy run --ssh-host` command from #439. Should be merged after those.
supercedes #417
Tested by migrating c2 back and forth, especially the second time worked like a charm :)

Guide on how to migrate chatmail to a new host

---

CHANGELOG.md
cmdeploy/src/cmdeploy/dovecot/dovecot.conf.j2

fix #441
I can't think of a good way to test this PR; the difference is mostly visible in stress tests I think.

dovecot: disable anvil authentication penalty

---

cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/chatmail.zone.j2
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/deploy.py

acmetool: only ask for iroh.$mail_domain cert if iroh_relay isn't set

---

cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/remote/rdns.py

DNS: fix _mta-sts TXT record on initial setup

---

.github/workflows/test-and-deploy-ipv4only.yaml
.github/workflows/test-and-deploy.yaml
CHANGELOG.md
README.md
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/tests/test_dns.py

DNS: add --all to cmdeploy dns

---

.github/workflows/test-and-deploy-ipv4only.yaml
.github/workflows/test-and-deploy.yaml
CHANGELOG.md
README.md
cmdeploy/src/cmdeploy/cmdeploy.py
cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/tests/test_dns.py

There is not really a reason not to show the recommended DNS records on `cmdeploy dns`. We can re-introduce the `--all` option or something similar when we think of one.

DNS: always show recommended DNS records

---

CHANGELOG.md
cmdeploy/src/cmdeploy/dns.py
cmdeploy/src/cmdeploy/remote/rdns.py

DNS: recommend DKIM record without space in between for some DNS web interfaces

---

cmdeploy/src/cmdeploy/acmetool/response-file.yaml.j2

to avoid the problem:
```
failed to request certificate: terms of service agreement is required, but user declined
```

update Let's encrypt Subscriber Agreement

---

CHANGELOG.md
cmdeploy/src/cmdeploy/nginx/nginx.conf.j2

There was an additional 8443 bind for the www redirect that was overlooked.
Also added the Changelog entry

Limit the bind for the HTTPS server on 8443 to 127.0.0.1 (additional)

---

CHANGELOG.md
chatmaild/src/chatmaild/echo.py
chatmaild/src/chatmaild/filtermail.py
chatmaild/src/chatmaild/tests/plugin.py
chatmaild/src/chatmaild/tests/test_filtermail.py
cmdeploy/src/cmdeploy/remote/rshell.py
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py
cmdeploy/src/cmdeploy/tests/online/test_2_deltachat.py
cmdeploy/src/cmdeploy/tests/plugin.py

this also simplifies the quota-exceeded test to not transfer tons of data and rather trick doveadm-quota calculation into considering a user over-quota.

enforce encryption for in-server mails

---

www/src/info.md

there is another mention of times in privacy.md,
however, there the gist is about that things are deleted, it is fine if that happens earlier there (also it is not excluded).
targets discussion from https://github.com/chatmail/relay/pull/504

add a hint that deletion may be earlier

---

CHANGELOG.md
cmdeploy/src/cmdeploy/postfix/master.cf.j2

Elsewhere in the master.cf we intentionally use 127.0.0.1 instead of localhost which is useful because it's possible that sometimes it could initially fail if IPv6 is enabled on the OS but these services are not bound to ::1

Postfix master.cf: use 127.0.0.1 for consistency

---

CHANGELOG.md
cmdeploy/src/cmdeploy/tests/online/test_0_login.py
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py

treat failure to connect to port 25 as "skip" test result. It's often happening with VPNs or some providers.

cleanly time out trying to connect to port 25 

---

CHANGELOG.md
cmdeploy/src/cmdeploy/__init__.py

According to #515, some providers misconfigure /etc/resolv.conf. With 9.9.9.9, at least one working DNS resolver is there.

DNS: add 9.9.9.9 to resolv.conf

---

chatmaild/src/chatmaild/notifier.py
chatmaild/src/chatmaild/tests/test_metadata.py

I wanted to create `enforceE2EEincoming` for every maildir folder in `/home/vmail/mail/DOMAIN/` I was not aware that there is a `pending_notifications` folder there, hard to realize when you have hundreds of folders there, it could happen to other people in general is better to be more resilient and just ignore such invalid files and delete them instead of crashing forever, dovecot process will fail badly then trying to connect to an nonexistent `/run/chatmail-metadata/metadata.socket`

avoid crash on spurious empty file in the pending_notifications dir

---

CHANGELOG.md
chatmaild/src/chatmaild/config.py
chatmaild/src/chatmaild/filtermail.py
chatmaild/src/chatmaild/ini/chatmail.ini.f
chatmaild/src/chatmaild/ini/override-testrun.ini
chatmaild/src/chatmaild/user.py

chatmaild: allow echobot to receive unencrypted messages by default

---

.github/ISSUE_TEMPLATE/bug_report.md
CHANGELOG.md
cmdeploy/src/cmdeploy/__init__.py
cmdeploy/src/cmdeploy/tests/online/test_1_basic.py
cmdeploy/src/cmdeploy/tests/plugin.py

This makes it easier to see which changes have already been deployed.

cmdeploy: upload chatmail/relay version to /etc 

---

cmdeploy/src/cmdeploy/__init__.py

- Added 'try' blocks around the 'git rev-parse' and 'git diff' commands that are run in deploy_chatmail().  If there is an error running rev-parse, git_hash is set to "unknown".  If there is an error running diff, git_diff is set to the null string.
- This allows the deployment process work in two scenarios that would otherwise fail with an exception:
- Systems where the 'git' command is not available.
- When running with a copy of the tree content of chatmail/relay, but without a copy of the .git directory.

feat: Add try blocks around Git commands in cmdeploy/__init__.py

---

CHANGELOG.md
scripts/initenv.sh

- The Python modules installed by initenv.sh require a compiler to build.
- Before proceeding with installation of Python dependencies, check whether the 'gcc' command is available by running it with the --version argument.  If it is not available, print a helpful message and exit.

feat: Check whether GCC is installed in initenv.sh

---

ARCHITECTURE.md

- For starters, this file is just a diagram of components of a chatmail server.  In the future, this document can grow into a more complete description of the architecture of the server, the deployment process, and the design intent behind what is and isn't in the code base.
- The name ARCHITECTURE.md is inspired by this article, which also has good suggestions about what to put in the file: https://matklad.github.io/2021/02/06/ARCHITECTURE.md.html

docs: Add ARCHITECTURE.md with diagram of components

---

.github/workflows/test-and-deploy-ipv4only.yaml
.github/workflows/test-and-deploy.yaml
CHANGELOG.md
cmdeploy/src/cmdeploy/cmdeploy.py

Pulled out of #614 - this speeds up `cmdeploy run` when you are already sure about your DNS records.

cmdeploy: `cmdeploy run` option to skip DNS checks
